export const JOB_STATUS = Object.freeze({
  PENDING:'PENDING', PREPARING_FLOW:'PREPARING_FLOW', UPLOADING_REFERENCE:'UPLOADING_REFERENCE',
  SETTING_PROMPT:'SETTING_PROMPT', GENERATING:'GENERATING', WAITING_RESULT:'WAITING_RESULT',
  CAPTURING_RESULT:'CAPTURING_RESULT', CACHING_RESULT:'CACHING_RESULT', DOWNLOADING:'DOWNLOADING',
  DONE:'DONE', RETRY_WAIT:'RETRY_WAIT', FAILED:'FAILED', PAUSED:'PAUSED'
});
export const BATCH_STATUS = Object.freeze({READY:'READY',RUNNING:'RUNNING',PAUSED_USER:'PAUSED_USER',PAUSED_ERROR:'PAUSED_ERROR',COMPLETED:'COMPLETED',STOPPED:'STOPPED'});
export const MSG = Object.freeze({
  BATCH_IMPORT:'BATCH_IMPORT',BATCH_START:'BATCH_START',BATCH_PAUSE:'BATCH_PAUSE',BATCH_RETRY:'BATCH_RETRY',BATCH_STOP:'BATCH_STOP',BATCH_GET_STATE:'BATCH_GET_STATE',
  FLOW_PREPARE:'FLOW_PREPARE',FLOW_UPLOAD_REFERENCE:'FLOW_UPLOAD_REFERENCE',FLOW_SET_PROMPT:'FLOW_SET_PROMPT',FLOW_GENERATE_CAPTURE:'FLOW_GENERATE_CAPTURE',FLOW_GENERATE_ARM:'FLOW_GENERATE_ARM',FLOW_GENERATE_WAIT:'FLOW_GENERATE_WAIT'
});
